### ISSUE TITLE
Does not work with Jacoco Code Coverage

### ISSUE THREAD

**Issue by jufan** [maiflai/gradle-scalatest#18]
I tried this plugin, it did run scalatest very well, but the Jacoco cannot generated code coverage report. Not sure if this plugin is not designed to work with Jacoco, if it did, could someone publish a sample configure for Gradle 1.9 ? Thanks.

**Comment by maiflai** [comment]
Hi,

Yes, the plugin isn't designed to work with Jacoco. In my experience the Jacoco reports didn't help much when reviewing Scala code.

This is because Jacoco covers bytecode that is generated by the Scala compiler, rather than the code that a developer wrote.

I prefer using a Scala-specific instrumentation tool such as https://github.com/scoverage/gradle-scoverage. These reports are much more focused on the written Scala code, and they work out of the box with this scalatest plugin.

That said, scoverage also has limitations, the main one being that it doesn't handle Java code in a mixed project. Support for multi-module testing is restricted to independent modules.

Jacoco itself is configured via JVM arguments, so it should be possible to enable it by hand. I can have a closer look if you must use Jacoco, but if so, can you upgrade to the latest gradle version?

Thanks,
Stu

**Comment by maiflai** [comment]
Closing this as it's been a month since the last comment
