### ISSUE TITLE
jacoco integration possible

### ISSUE THREAD

**Issue by kknd22** [maiflai/gradle-scalatest#26]
I have the main source in java and using scalatest for testing with gradle build and use jacoco for coverage. following the example from: [link to example in github!]
https://github.com/sebastianharko/gradle-sonar-java-jacoco-scalatest-junit/blob/master/build.gradle
however, whenever I use this plugin, it will run all test and report well. but jacocoTestReport is always SKIPPED. Any idea? Thanks
-Chris

**Comment by maiflai** [comment]
Hi,

Please could you try changing the order in which you apply the plugins? I'm seeing some interesting behaviour locally.

I suspect that at the moment you have the following:

```groovy
apply plugin: 'jacoco'
apply plugin: 'com.github.maiflai.scalatest'
```

If so, please could you switch the order such that scalatest is applied first? When I try this locally I receive the following error message:

> Malformed class name

Thanks,
Stu.

**Comment by maiflai** [comment]
If that doesn't work, you might try leaving the order as is, but manually modifying the `Test` task as below:

```groovy
test {
  doFirst {
    if (jacoco.enabled) {
      jvmArgs jacoco.getAsJvmArg()
    }
  }
}
```

Note that you need to include the `test` task in your command; jacocoTestReport does not explicitly depend on the tests and won't do anything if tests are not run.

`./gradlew clean test jacocoTestReport`

**Comment by kknd22** [comment]
Thanks Stu, It works like a charm. Thanks for the help.
One more thing if you can, if I have java junit test co-exist along with scalatest code, I was not able to run both test using 'gradle test', (if use apply plugin: "com.github.maiflai.scalatest", only scalatest will be run, otherwise, have to add junit annotation to the scalatest for the junit test to execute scalatest
Thanks
 -Chris

**Comment by maiflai** [comment]
Sorry, that particular mode is not directly supported because the plugin uses ScalaTest itself to write reports rather than plugging into the gradle test infrastructure. This means that the report directories clash.

In the past I've recommended being consistent within a single project - create a new Scala-specific project and use one test framework in it.

If you must have JUnit and ScalaTest in the same project then either annotate your tests (and run the risk of forgetting the annotation), or create a new `Test` task and apply the `ScalaTestAction` directly to it as this particular plugin does. This is, however, internal behaviour and therefore unsupported...

re: Jacoco, I will address this issue in a future release; it should 'just work' - sorry, and thanks for reporting it.

**Comment by maiflai** [comment]
Hi,

This has now been released, please can I close the issue?

Thanks,
Stu

**Comment by kknd22** [comment]
I will check it out. Please close it. Thanks
-Chris
