### ISSUE TITLE
Passing config map values

### ISSUE THREAD

**Issue by PGrimes** [maiflai/gradle-scalatest#32]
I am trying to pass a config map value using this plugin, but have not been able to make it work.  Is this supported?

http://doc.scalatest.org/2.2.6/#org.scalatest.Suite@configMapSection

**Comment by maiflai** [comment]
Not as yet, sorry. I'll try to take a look this weekend.

**Comment by maiflai** [comment]
Please could you have a look at https://github.com/maiflai/gradle-scalatest/pull/33 and see if the documentation looks ok?

**Comment by PGrimes** [comment]
This looks great.  I appreciate the quick turn around on this.

**Comment by maiflai** [comment]
You're welcome. 

I think I remember looking at configMap before, but I prefer to use my normal application configuration library in tests; this means a couple of things:

* a single means of configuration
* common behaviour when running from Gradle or an IDE

And on the downside I now have multiple configuration files. I try to avoid using tokenised configuration because you again end up with Gradle / IDE conflicts.

**Comment by maiflai** [comment]
Please can I close this issue?

Thanks,
Stu

**Comment by maiflai** [comment]
Closing now.
