### ISSUE TITLE
Spec is only run if the class ends in "Spec"

### ISSUE THREAD

**Issue by will-sargent-eero** [maiflai/gradle-scalatest#79]
If you have a class that is called "Spec22" then the plugin will not find it.

**Comment by will-sargent-eero** [comment]
https://github.com/maiflai/gradle-scalatest/blob/cae43c9ec3e1933cd99cf4dc1ffe4df2f1112a0c/src/main/groovy/com/github/maiflai/ScalaTestAction.groovy#L149

**Comment by maiflai** [comment]
Sorry for the delay. 

I'm not sure that what you have above is strictly and completely true? I didn't find it easy to shim Gradle's test filtering logic into ScalaTest. It may be that you need to use a substring of the test name in order to run a single spec.

Do you have a complete example that I could take a closer look at please?

Thanks,
Stu.

**Comment by will-sargent-eero** [comment]
@maiflai added example project https://github.com/will-sargent-eero/demo-scalatest-project

**Comment by maiflai** [comment]
Thanks - have added a test and fix on master. I'll see if I can get a release out soon.

**Comment by maiflai** [comment]
deployed 0.26 with a fix, please could you see if it addresses your issue?

thanks,
Stu

**Comment by will-sargent-eero** [comment]
Fixed by https://github.com/maiflai/gradle-scalatest/commit/22a25c88a1b03d289b102acef9fd5cf97f233fdc
